#!/bin/sh

if [ -x /etc/init.d/evopedia ]
then
    update-rc.d $OPT evopedia defaults > /dev/null
    [ -x /etc/init.d/evopedia ] && /etc/init.d/evopedia start
    #[ -x /sbin/start ] && /sbin/start --quiet evopedia
fi

exit 0
